apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: beet
  name: beet
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: beet
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: beet
    spec:
      containers:
      - image: beethub/beet:0.0.29
        name: beet
        resources: {}
status: {}
